"""Add advanced metrics

Revision ID: 9e564d1e8374
Revises: 003_correlation_id
Create Date: 2026-05-01 21:28:44.245213
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9e564d1e8374'
down_revision: Union[str, None] = '003_correlation_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eval_results', sa.Column('semantic_similarity', sa.Float(), nullable=True))
    op.add_column('eval_results', sa.Column('pii_detected', sa.Boolean(), nullable=True))
    op.add_column('eval_runs', sa.Column('semantic_similarity_score', sa.Float(), nullable=True))
    op.add_column('eval_runs', sa.Column('pii_leakage_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eval_runs', 'pii_leakage_score')
    op.drop_column('eval_runs', 'semantic_similarity_score')
    op.drop_column('eval_results', 'pii_detected')
    op.drop_column('eval_results', 'semantic_similarity')
    # ### end Alembic commands ###
